services:
  db:
    image: postgres:15
    container_name: walk-profile-db
    env_file:
      - .env
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "walk-user", "-d", "walk-profile" ]
      interval: 3s
      timeout: 1s
      retries: 1
    volumes:
      - ./docker/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql

  walk-profile:
    build:
      context: .
    container_name: walk-profile-app
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    command: ["/walk-profile/docker/app.sh"]
    ports:
      - 80:8000
