services:
  db:
    image: postgres:15
    container_name: walk-profile-db
    env_file:
      - .env
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "walk-user", "-d", "walk-profile" ]
      interval: 3s
      timeout: 1s
      retries: 1
    networks:
      - walk-network
    volumes:
      - ./docker/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql

  redis:
    image: redis:7.2
    container_name: walk-redis
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 2s
      retries: 3
    networks:
      - walk-network

  walk-profile:
    build:
      context: .
    container_name: walk-profile-app
    depends_on:
      db:
        condition: service_healthy
    networks:
      - walk-network
    env_file:
      - .env
    command: ["/walk-profile/docker/app.sh"]
    ports:
      - 8001:8001

networks:
  walk-network:
    external: true
